# fly.toml app configuration file generated for dolomites-nats-cluster on 2023-08-09T16:15:35+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dolomites-nats-cluster"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 3
  processes = ["app"]
